matematikk-mooc/kpas-api

- resources/js/components/GroupSelector.vue
- resources/js/components/RoleSelector.vue
- resources/js/views/GroupEnrollView.vue
- resources/sass/app.scss
Added new heading to separate the two separate radio buttons lists. Slightly increased the grey iframe area below the 'submit' button for aesthetic purposes.
> Improvement to kpas lti

- app/Barnehage.php
- app/Http/Controllers/SkolerController.php
- database/migrations/2020_06_15_112757_create_barnehages_table.php
- routes/api.php
Implements https://jira.udir.no/browse/KURSP-83
> barnehage kpas api

- app/Http/Controllers/Lti3Controller.php
- app/Http/Controllers/SkolerController.php
- app/Http/Middleware/LtiMiddleware.php
- composer.json
- composer.lock
- routes/api.php
This fixes issue in jirra https://jira.udir.no/browse/KURSP-113
> Fix custom fields in kpas

- app/Console/Commands/FetchNsrData.php
- app/Console/Kernel.php
- app/Services/DataNsrService.php
- routes/api.php
- run_scheduler.sh
Schedules data fetching daily at 1:00 am and runs in background
> Performance improvment for fetching nsr data

- .gitignore
- app/Http/Controllers/GroupController.php
- app/Http/Controllers/Lti3Controller.php
- database/configs/config_platform.json
- resources/js/components/GroupSelector.vue
- routes/api.php
https://jira.udir.no/browse/KURSP-114
> change school_category_id to institution_category_id

- package-lock.json
- package.json
Upgraded some packages to fix security vulnerabilities suggested in Github.
> Upgraded some packages to fix security vulnerabilities 

- app/Http/Kernel.php
- app/Http/Middleware/CheckToken.php
- routes/api.php
Requests to sensitive api endpoints should have an access token.
> add security to the sensitive api endpoints

- app/Http/Controllers/FacultyController.php
- app/Http/Middleware/CheckToken.php
https://jira.udir.no/browse/KURSP-119
> display faculty list if it is configured in course settings

- app/Http/Controllers/SkolerController.php
filter skoler where ErVideregaaendeSkole or ErGrunnSkole is true
> filter skoler where ErVideregaaendeSkole or ErGrunnSkole is true

- app/Http/Controllers/SkolerController.php
fixes https://jira.udir.no/secure/RapidBoard.jspa?rapidView=260&projectKey=KURSP&view=detail&selectedIssue=KURSP-120
> filter_obsolete_counties

- app/Http/Controllers/SkolerController.php
Filter obsolete counties by fylkesNr
https://data-nsr.udir.no/swagger/ui/index#!/Fylke/FylkeApi_GetFylker
> Filter fylke by FylkesNr

- app/Http/Controllers/CommandController.php
- app/Http/Controllers/Lti3Controller.php
- routes/api.php
This fixes https://jira.udir.no/browse/KURSP-151
> Fix php artisan route:cache issue

- .htaccess
Readding .htaccess, as there was a .htaccess on the server that not tracked by git
When new .htaccess file was added to git the one on the server was overwritten and it's config lost.
> Readding .htaccess

- app/Repositories/SubtitlesRepository.php
Denne videoen returnerer en tom body: https://bibsys.instructure.com/courses/337/pages/3-dot-2-video-barn-som-produsenter?module_item_id=23478
> Handle case where body is present but empty.

- app/Http/Controllers/VimeoController.php
> Staging branch

- app/Http/Controllers/VimeoController.php
- package-lock.json
Some vimeo videos contain tags in the subtitles. F.ex this one: https://vimeo.com/517074838 contains
<i><c.yellow>"lyder fra hjemmelagde instrument"</c></i> 
I now use the php function strip_tags to remove all such tags.
> Strip subtitles for tags and put them inside CDATA sections in the xml code

- .gitignore
- app/Http/Controllers/DeepController.php
- app/Http/Controllers/Lti3Controller.php
- composer.json.dev
- composer.json.prod
- composer.lock
- resources/js/views/GroupEnrollView.vue
- resources/views/main/deep.blade.php
- routes/api.php
- routes/web.php
- vendor-repo/.gitignore
Gjør at vi kan embedde KPAS på en innholdsside.
> Deep linking

- app/Services/CanvasService.php
- app/Services/DiplomaService.php
Unpublished items are not returned by Canvas so we do not need to ignore them. Always give teachers and admins access to diploma. Refactor logic to make it easier to understand.
NB. Must be tested on Canvas prod as it is not possible to be a student on test plattform.
> Ignore unpublished modules. 

- deploy.sh
Reverts matematikk-mooc/kpas-api#185
> Revert "deploy.sh composer version"

- composer.json
- composer.json.dev
- composer.json.prod
- composer.lock
- docker/.env.example
Reverts matematikk-mooc/kpas-api#187
> Revert "php 8.0"

- resources/js/components/FacultySelector.vue
Update v-model in FacultySelector to support vue3, using modelValue
> KURSP-724: FacultySelector v-model update

- docker-prod/ssh_bash_profile
- prod.Dockerfile
Now, new ssh sessions will start in /var/www/html directory
> Added .bash_profile for prod docker image

- app/Models/CanvasCourse.php
- app/Models/JoinCanvasGroupUser.php
- database/migrations/2022_12_21_154239_create_canvas_courses_table.php
- database/migrations/2022_12_21_161905_create_join_canvas_group_users_table.php
Add database tables for canvas_courses and join_canvas_group_users
> KURSP-742: database tables

- app/Console/Commands/FetchCanvasData.php
- app/Console/Kernel.php
- app/Models/CanvasCourse.php
- app/Models/JoinCanvasGroupUser.php
- app/Services/CanvasService.php
- database/migrations/2022_12_21_154239_create_canvas_courses_table.php
- database/migrations/2022_12_21_161905_create_join_canvas_group_users_table.php
* Added a new Laravel Command for fetching data from Canvas
* Added getAllCourses() to CanvasService
* Logic for fetching all courses from Canvas and inserting them into DB
* Logic for fetching user<->group relationships from Canvas and inserting them into DB
> KURSP-743: Add nightly process for fetching Canvas courses:

- app/Models/CanvasCourse.php
- app/Models/CanvasUserMergeToken.php
- app/Models/Group.php
- app/Models/JoinCanvasGroupUser.php
- app/Models/Survey.php
- app/Models/SurveyQuestion.php
- app/Models/SurveySubmission.php
- app/Models/SurveySubmissionData.php
- database/migrations/2023_01_12_174612_remove_relations_between_survey_and_canvas_data.php
- routes/api.php
In addition, I've fixed a small bug in the API HTTP Routes, and added PHPDocs for Model fields
> KURSP-750: Remove relations between survey tables and Canvas tables:

- database/migrations/2023_01_19_095723_update_title_form_in_surveys_table.php
make db column title_form nullable
> KURSP-754: title form nullable

- composer.json
- composer.json.dev
- composer.json.prod
- composer.lock
- package-lock.json
update dependencies indicated by github dependabot
> KURSP-488: update dependencies

- resources/js/views/DashboardView.vue
make sure groups are ready before returning view
> KURSP-749: returning view before groups are ready

- resources/js/components/charts/GroupedBarChart.vue
- resources/js/views/DashboardView.vue
> KURSP-749: remove 0 labels

- app/Http/Controllers/GroupController.php
- routes/api.php
new endpoint to get all groups
> KURSP-760: get all groups

- app/Http/Requests/Survey/AddSurveyRequest.php
- app/Models/Survey.php
- app/Repositories/CanvasRepository.php
- app/Repositories/SurveyRepository.php
- app/Services/CanvasService.php
- database/migrations/2023_02_10_142136_add_module_id_to_surveys.php
- resources/js/views/DashboardView.vue
- resources/js/views/KpasEmbedView.vue
- resources/views/main/deep.blade.php
Add column module_id to surveys table
> KURSP-762 and KURSP-763: Update database and embed view with module selector

- app/Dto/GroupDto.php
- app/Http/Controllers/GroupController.php
- app/Models/Group.php
- database/migrations/2023_02_15_120907_add_county_community_ids_to_groups.php
- resources/js/components/GroupSelector.vue
add fields course_id, county_id, community_id
> KURSP-770: update db table groups

- app/Http/Controllers/Lti3Controller.php
- app/Services/AdminDashboardService.php
- config/constants.php
- resources/js/app.js
- resources/js/views/AdminDashboardView.vue
- resources/js/views/KpasEmbedView.vue
- resources/views/main/admin-dashboard.blade.php
- resources/views/main/deep.blade.php
Add new lti template for admin dashboard
> KURSP-768: Admin dashboard lti

- resources/js/views/KpasEmbedView.vue
removed a needed comma when resolving conflicts
> KURSP-768: merge confict fix

- resources/js/components/DashboardGroupSelect.vue
add cookie to api calls in DasboardGroupSelect
> KURSP-764: add cookie to api calls

- app/Http/Controllers/ModuleController.php
- app/Http/Controllers/SurveyController.php
- app/Services/ModuleService.php
- resources/js/views/AdminDashboardView.vue
- resources/views/main/admin-dashboard.blade.php
> Merge admin dashboard

- resources/js/views/AdminDashboardView.vue
Only let roles Admin and Udirforvalter load admin dashboard.
> KURSP-767: Restrict admin dashboard

- database/migrations/2023_03_21_093907_add_index_to_skoles.php
- database/migrations/2023_03_21_113752_add_index_to_barnehages.php
add index to kpas db tables skoles and barnehages on nsrid
> KURSP-133: add index to skoles and barnehages tables

- app/Http/Controllers/Lti3Controller.php
- app/Http/Middleware/Lti3Middleware.php
- composer.lock
- resources/js/app.js
- resources/js/views/NoCookies.vue
- resources/views/main/nocookies.blade.php
Add possibility to run LTI without 3rd party cookies, using Canvas platform postMessage storage
> KURSP-669: no 3rd party cookies

- app/Http/Middleware/Lti3Middleware.php
- resources/js/views/NoCookies.vue
- resources/views/main/nocookies.blade.php
remove hardcoded platform host
> KURSP-669: platform host

- resources/js/components/charts/BarChart.vue
- resources/js/views/AdminDashboardView.vue
- resources/js/views/DashboardView.vue
Changes to skoleleder dashboard, no scrolling inner framee, single question barchart improved design
> KURSP-790: design changes dashboard

- resources/js/components/CurrentGroup.vue
Allways show current groups in GroupEnrollView in the same order
> KURSP-379: Current groups fixed order

- app/Dto/GroupDto.php
- app/Models/Group.php
- database/migrations/2023_05_15_120124_add_orgnr_to_groups.php
- resources/js/components/GroupSelector.vue
Add org_id column to groups table in database
> KURSP-523: Add org_nr to groups

- app/Models/Category.php
- app/Models/CourseCategory.php
- app/Models/CourseFilter.php
- app/Models/CourseSettings.php
- app/Models/Filter.php
- database/migrations/2023_08_21_125305_create_course_settings_table.php
- database/migrations/2023_08_21_131215_create_filters_table.php
- database/migrations/2023_08_21_131507_create_course_filters_table.php
- database/migrations/2023_08_21_131817_create_categories_table.php
- database/migrations/2023_08_21_132143_create_course_categories_table.php
Add migrations and models for coursesettings, filters, coursefilters, categories and coursecategories
> KURSP-862: expand db with tables for course settings

- app/Http/Controllers/CourseSettingsController.php
- app/Http/Requests/CourseSettings/CourseSettingsRequest.php
- app/Models/Category.php
- app/Models/CourseCategory.php
- app/Models/CourseFilter.php
- app/Models/CourseSettings.php
- app/Models/Filter.php
- app/Repositories/CourseSettingsRepository.php
- database/migrations/2023_08_23_091230_add_unique_to_course_settings.php
- database/migrations/2023_08_23_091531_add_foreign_key_to_course_categories.php
- database/migrations/2023_08_23_091838_add_foreign_key_to_course_filters.php
- database/migrations/2023_08_23_161630_add_type_to_filters.php
- routes/api.php
Endpoints for getting and setting coursesettings, with category and filters
> KURSP-867: Endpoints for course settings

- app/Http/Controllers/Lti3Controller.php
- app/Services/CourseSettingsService.php
- config/constants.php
- resources/views/main/coursesettings.blade.php
> KURSP-864: course settings blade

- resources/js/components/CourseSettingsCategoryCreate.vue
- resources/js/views/CourseSettingsView.vue
course category and image cannot be empty
> KURSP-908: course settings empty fields

- resources/js/components/GroupSelector.vue
- Handle set county to null
- Handle set community + institution to null
> Added null validation to the group selector when dropdown is cleared

- resources/js/views/DashboardView.vue
- Updated label to show group type if it is not already apart of the group name, so that the users know the scope/level
- Ignore group too small check if it is checking for municipality view
- If the institution is set to other, load data on municipality level instead
> DIT-30: Show dashboard for municipality if institution is set to other

- docker-compose.yml
- resources/js/views/SurveyView.vue
- resources/sass/survey.scss
- Aligned radiobuttons in surveys.
> DIT-248: Radiobuttons.

- app/Http/Requests/CourseSettings/CourseSettingsRequest.php
- resources/js/views/CourseSettingsView.vue
- Resized input box to fit page better
- Multiple lines now supported, so all text is displayed.
- Added character counter that shows the limit.
- Set maxlength to further communicate field limit
> DIT-432: Emneinstillinger.
